# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160111_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='accounts.Member'),
        ),
    ]
